package env

const (
	BACKEND_HOST = "BACKEND_HOST"
	BACKEND_PORT = "BACKEND_PORT"

	K8S_API_SERVER_HOST = "K8S_API_SERVER_HOST"
	K8S_API_SERVER_PORT = "K8S_API_SERVER_PORT"
	K8S_PROTOCOL        = "K8S_PROTOCOL"

	//    PROMETHEUS_HOST = "192.168.0.1"
	//    PROMETHEUS_PORT = 10000

	USER_MANAGER_HOST = "USER_MANAGER_HOST"
	USER_MANAGER_PORT = "USER_MANAGER_PORT"

	USER_DB_HOST = "USER_DB_HOST"
	USER_DB_PORT = "USER_DB_PORT"

	REGISTRY_HOST = "REGISTRY_HOST"
	REGISTRY_PORT = "REGISTRY_PORT"

	REGISTRY_SERVER_HOST = "REGISTRY_SERVER_HOST"
	REGISTRY_SERVER_PORT = "REGISTRY_SERVER_PORT"

//    EXT_CONFIG_PATH = "/etc/umi/ext_config.json"

//    DOCKER_REGISTRY_HOST = "192.168.0.1"
//    DOCKER_REGISTRY_PORT = 10002
)

//enum resint
const (
	POD = iota
	PODTEMPLATE
	REPLICATIONCONTROLLER
	SERVICE
	ENDPOINT
	NODE
	BINDING
	EVENT
	LIMITRANGE
	RESOURCEQUOTA
	NAMESPACE
	SECRET
	SERVICEACCOUNT
	PERSISTENTVOLUME
	PERSISTENTVOLUMECLAIM
	DELETEOPTIONS
	COMPONENTSTATUS
	CONFIGMAP
)
